// This file is auto-generated by @hey-api/openapi-ts

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/extendeverything/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type VersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/extendeverything/api/v1/version';
};

export type VersionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type VersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type VersionResponse = VersionResponses[keyof VersionResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44314' | (string & {});
};