// This file is auto-generated by @hey-api/openapi-ts

export type PingResponse = (string);

export type PingError = (unknown);

export type VersionResponse = (string);

export type VersionError = (unknown);